### ISSUE TITLE
Consistent naming of steps/commands

### ISSUE THREAD

**Issue by vineetbansal** [skinniderlab/CLM#121]
At some point, we can remove all mentions of "inner_" in the command/step names, and go with the most logical name (it's probably still best to keep names like `write_nn_tc` so Michael can cross-reference his original implementation with the latest ones).

**Comment by vineetbansal** [comment]
@anushka255 , @skinnider - one of the problems I've had these past couple of months is not being able to retain in my head for any extended period of time what step of the pipeline does, at a high level. Part of this is because the names of the steps don't make it very sticky (other than the inconsistent naming like `inner-*` or inclusion of implementation details like `RNN`..) and might be a barrier for future contributors working on this.

I'm leaning towards single verbs, but also feel like the name should intuitively tell us the intention of the step including the paths that should go in and come out of it. So we can use compound words if it helps clear the matter. (I'm not particularly thrilled with `collect`/`combine`, for example). Here's my first stab at it. Can you let me know your thoughts?

![dag](https://github.com/skinniderlab/CLM/assets/318858/458267fc-ef7c-4ab3-80a1-4107685ac3e2)

I'm using 2 instances of the steps wherever I can (e.g. train seeds/sample seeds/min freq) to make the branching representative of what might happen. I'm also only including the steps minus the evaluation steps here (which we can handle a bit later).

**Comment by skinnider** [comment]
This makes a lot of sense to me. A couple suggestions:
- I think a longer name for the "generate" step would help with clarity (perhaps "generate-training-sets" or "generate-splits"?)
- for "collect/combine", maybe clearer could be "merge-across-seeds" vs. "merge-across-folds"?
