### ISSUE TITLE
% novel/% valid

### ISSUE THREAD

**Issue by skinnider** [skinniderlab/CLM#168]
`calculate_outcomes` is being run on the output of `collect_tabulated_molecules`, which means % novel/% valid are constant and 1. 
We should either (1) provide separately as input a single sample of 500k "raw" SMILES (without removing invalid ones and canonicalizing) or (2) just remove these plots

**Comment by vineetbansal** [comment]
Note: `--max_molecules 500000` in `rule prep_outcome_freq`

**Comment by anushka255** [comment]
`collect_tabulated_molecules` now saves `invalid`/`known` SMILES as well. This combined with the `novel` SMILES is being used in `calculate_outcomes` to compute %novel/ %valid.
