### ISSUE TITLE
Collapse prep/write steps in model evaluation

### ISSUE THREAD

**Issue by vineetbansal** [skinniderlab/CLM#188]
Consider merging:

In general, the `plot*` scripts could take the output of `Snakefile_data`, Specific examples:

  - `write_outcome_distr` and `calculate_outcome_distrs` could collapse
  -  `prep_nn_tc`/`write_nn_tc`/`plot_write_nn_tc`
  - any others you can think of.

**Comment by anushka255** [comment]
This issue has been dealt with. Thanks!
